#!/usr/bin/env python3

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess


def command_output(arguments):
    return subprocess.check_output(arguments, text=True).strip()


def toolchain(crate):
    configuration = (crate / "rust-toolchain.toml").read_text()
    match = re.search(r'^channel\s*=\s*"([^"]+)"', configuration, re.MULTILINE)
    if match is None:
        raise SystemExit("rust-toolchain.toml does not declare channel")
    return match.group(1)


def license_files(root):
    prefixes = ("license", "copying", "unlicense", "copyright")
    return sorted(file for file in root.iterdir() if file.is_file() and file.name.lower().startswith(prefixes))


def digest(content):
    return hashlib.sha256(content).hexdigest()


def normalized(content):
    lines = content.decode("utf-8").replace("\r\n", "\n").replace("\r", "\n").split("\n")
    return ("\n".join(line.rstrip() for line in lines).rstrip() + "\n").encode()


def collect(root):
    bridge = root / "internal/oxc"
    crate = bridge / "rust"
    rust = toolchain(crate)
    metadata = json.loads(command_output([
        "cargo", "+" + rust, "metadata", "--locked", "--format-version", "1",
        "--manifest-path", str(crate / "Cargo.toml"),
    ]))
    notices = {}
    packages = []
    oxc_license = normalized((bridge / "LICENSE-OXC").read_bytes())
    oxc_digest = digest(oxc_license)
    notices[oxc_digest] = oxc_license
    for package in sorted(metadata["packages"], key=lambda item: (item["name"], item["version"])):
        if package["source"] is None:
            continue
        files = license_files(Path(package["manifest_path"]).parent)
        if not files and package["name"].startswith("oxc_"):
            hashes = [oxc_digest]
        else:
            hashes = []
            for file in files:
                content = normalized(file.read_bytes())
                value = digest(content)
                notices[value] = content
                hashes.append(value)
        if not hashes:
            raise SystemExit(package["name"] + " " + package["version"] + " has no packaged license notice")
        packages.append((package["name"], package["version"], package["license"] or "UNKNOWN", sorted(set(hashes))))

    sysroot = Path(command_output(["rustc", "+" + rust, "--print", "sysroot"]))
    rust_notice = normalized((sysroot / "share/doc/rust/COPYRIGHT-library.html").read_bytes())
    rust_digest = digest(rust_notice)
    notices[rust_digest] = rust_notice

    output = [
        "Third-party notices for the slopradar native Oxc archives\n",
        "Generated by scripts/collect-oxc-licenses.py from internal/oxc/rust/Cargo.lock and Rust " + rust + "; line endings and trailing whitespace are normalized.\n",
        "\n",
        "package\tversion\tdeclared license\tnotice SHA-256\n",
    ]
    for name, version, license_expression, hashes in packages:
        output.append("\t".join([name, version, license_expression, ",".join(hashes)]) + "\n")
    output.append("\t".join(["rust-std", rust, "Apache-2.0 OR MIT and bundled exceptions", rust_digest]) + "\n")
    for value in sorted(notices):
        output.extend(["\n", "=" * len(value) + "\n", "notice SHA-256 " + value + "\n", "=" * len(value) + "\n", "\n"])
        output.append(notices[value].decode("utf-8"))
        if not output[-1].endswith("\n"):
            output.append("\n")
    return "".join(output).encode()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    destination = root / "internal/oxc/THIRD_PARTY_LICENSES.txt"
    content = collect(root)
    if args.check:
        if not destination.exists() or destination.read_bytes() != content:
            raise SystemExit("native Oxc third-party notices are stale; run scripts/collect-oxc-licenses.py")
        print("native Oxc third-party notices verified")
        return
    destination.write_bytes(content)
    print(str(destination) + " " + digest(content))


if __name__ == "__main__":
    main()
